version: "3.8"

volumes:
  mc_users:

services:
  user_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_db
    volumes:
      - mc_users:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  app:
    restart: always
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - user_db
    environment:
      SPRING_DATA_SOURCE_URL: 'jdbc:postgresql://user_db:5432/user_db'
      SPRING_DATA_SOURCE_USERNAME: 'root'
      SPRING_DATA_SOURCE_PASSWORD: 'root'
      SPRING_FLYWAY_URL: 'jdbc:postgresql://user_db:5432/user_db'
      SPRING_FLYWAY_USER: 'root'
      SPRING_FLYWAY_PASSWORD: 'root'
      JAVA_OPTS: '-Xmx512m'